module.exports = {
  purge: false,
  theme: {
    colors: {
      black: "#000",
      white: "#fff",
    },
    extend: {},
  },
  variants: {},
  plugins: [],
  corePlugins: {
    fontWeight: false,
    fontFamily: false,
    fontSize: false,
    fontSmoothing: false,
    fontWeight: false,
    letterSpacing: false,
    lineHeight: false,
    listStyleType: false,
    listStylePosition: false,
    placeholderColor: false,
    placeholderOpacity: false,
    textOpacity: false,
    textDecoration: false,
    textTransform: false,
    verticalAlign: false,
    whitespace: false,
    wordBreak: false,
  },
}
